# Picking the DatasetL fetch_lfw_people

In [25]:
# Picking the DatasetL fetch_lfw_people
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.datasets import fetch_lfw_people
dataset = fetch_lfw_people(min_faces_per_person=70, resize=0.4)

for name in dataset.target_names:
    print(name)


Ariel Sharon
Colin Powell
Donald Rumsfeld
George W Bush
Gerhard Schroeder
Hugo Chavez
Tony Blair


In [26]:
data_shape = dataset['data'].shape
print("Data Loaded: {2}\nTarget Loaded: {3}\nSamples: {0}\nFeatures: {1}\n"
      .format(data_shape[0], data_shape[1], "data" in dataset.keys(), "target" in dataset.keys()))

Data Loaded: True
Target Loaded: True
Samples: 1288
Features: 1850



In [27]:
x = dataset['data']
y = dataset['target']
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [28]:
#FEATURE SCALING 
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

# Create a MLP with the same settings as the sample workbook. (Everything default, 3 hidden layers with 30 neurons each). Train and Test

In [29]:
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30))

In [30]:
mlp.fit(x_train,y_train)

MLPClassifier(hidden_layer_sizes=(30, 30, 30))

In [31]:
predictions = mlp.predict(x_test)

In [34]:
from sklearn.metrics import r2_score
print(confusion_matrix(y_test,predictions))
print()
from sklearn.metrics import r2_score
print("R2 Score:",r2_score(y_test, predictions))
print()
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[ 16   2   4   0   1   0   1]
 [  0  54   1   5   0   0   1]
 [  1   0  21   5   3   0   0]
 [  1   3   2 113   4   1   1]
 [  1   0   1   2  18   2   4]
 [  0   0   0   2   1  15   0]
 [  0   2   1   4   1   2  26]]

R2 Score: 0.6311847574107351

              precision    recall  f1-score   support

           0       0.84      0.67      0.74        24
           1       0.89      0.89      0.89        61
           2       0.70      0.70      0.70        30
           3       0.86      0.90      0.88       125
           4       0.64      0.64      0.64        28
           5       0.75      0.83      0.79        18
           6       0.79      0.72      0.75        36

    accuracy                           0.82       322
   macro avg       0.78      0.76      0.77       322
weighted avg       0.82      0.82      0.82       322



# Increase your learning rate (alpha) to 0.1. Retrain and retest

In [35]:
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30),alpha=0.1)
mlp.fit(x_train,y_train)
predictions = mlp.predict(x_test)
from sklearn.metrics import r2_score
print(confusion_matrix(y_test,predictions))
print()
from sklearn.metrics import r2_score
print("R2 Score:",r2_score(y_test, predictions))
print()
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[ 16   4   2   0   1   0   1]
 [  0  52   0   5   0   0   4]
 [  1   1  20   6   2   0   0]
 [  1   5   2 112   2   0   3]
 [  0   0   2   4  20   0   2]
 [  0   0   0   2   2  14   0]
 [  1   2   1   3   1   1  27]]

R2 Score: 0.5284906928574369

              precision    recall  f1-score   support

           0       0.84      0.67      0.74        24
           1       0.81      0.85      0.83        61
           2       0.74      0.67      0.70        30
           3       0.85      0.90      0.87       125
           4       0.71      0.71      0.71        28
           5       0.93      0.78      0.85        18
           6       0.73      0.75      0.74        36

    accuracy                           0.81       322
   macro avg       0.80      0.76      0.78       322
weighted avg       0.81      0.81      0.81       322



# Change your learning rate back to default. Decrease your momentum to 0.1. Retrain and retest.

In [36]:
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30),alpha=0.0001, momentum=0.1)
mlp.fit(x_train,y_train)
predictions = mlp.predict(x_test)
from sklearn.metrics import r2_score
print(confusion_matrix(y_test,predictions))
print()
from sklearn.metrics import r2_score
print("R2 Score:",r2_score(y_test, predictions))
print()
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[ 15   5   2   1   1   0   0]
 [  0  52   0   5   0   0   4]
 [  1   2  19   5   2   0   1]
 [  1   3   2 114   3   0   2]
 [  0   0   2   1  18   2   5]
 [  0   0   0   3   5   9   1]
 [  2   2   1   3   2   1  25]]

R2 Score: 0.49205086349981486

              precision    recall  f1-score   support

           0       0.79      0.62      0.70        24
           1       0.81      0.85      0.83        61
           2       0.73      0.63      0.68        30
           3       0.86      0.91      0.89       125
           4       0.58      0.64      0.61        28
           5       0.75      0.50      0.60        18
           6       0.66      0.69      0.68        36

    accuracy                           0.78       322
   macro avg       0.74      0.69      0.71       322
weighted avg       0.78      0.78      0.78       322



# Keep momentum the same. Increase max_iter to 1000. Retrain and retest.

In [37]:
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30),alpha=0.0001, momentum=0.1,max_iter=1000)
mlp.fit(x_train,y_train)
predictions = mlp.predict(x_test)
from sklearn.metrics import r2_score
print(confusion_matrix(y_test,predictions))
print()
from sklearn.metrics import r2_score
print("R2 Score:",r2_score(y_test, predictions))
print()
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[ 15   5   3   0   1   0   0]
 [  0  50   1   5   0   1   4]
 [  1   0  22   5   2   0   0]
 [  0   2   3 115   4   0   1]
 [  0   0   2   4  17   2   3]
 [  0   1   0   2   2  12   1]
 [  0   2   2   3   2   0  27]]

R2 Score: 0.5792856065074553

              precision    recall  f1-score   support

           0       0.94      0.62      0.75        24
           1       0.83      0.82      0.83        61
           2       0.67      0.73      0.70        30
           3       0.86      0.92      0.89       125
           4       0.61      0.61      0.61        28
           5       0.80      0.67      0.73        18
           6       0.75      0.75      0.75        36

    accuracy                           0.80       322
   macro avg       0.78      0.73      0.75       322
weighted avg       0.80      0.80      0.80       322



# Now try to build a model with the highest level of accuracy you can. You can change any of the parameters including max_iter, alpha, momentum, and hidden layers. Take your time testing different configurations until you find one you like.



NOTE*: Since grid search is being used, best would be not to run this code, just run the last block of this code, cause it will take a lot of time and can cause an error is the system does not have required memory.

In [38]:
parameter_space = {
    'hidden_layer_sizes': [(500,500,500), (400,400,400),(300,300,300),(200,200,200)],
    'momentum':[0.9,0.8,0.6,0.5],
    'alpha': [0.0001, 0.001],
    'max_iter':[1000,2000,3000,4000]
}

In [39]:
from sklearn.model_selection import GridSearchCV
mlp = MLPClassifier()
clf = GridSearchCV(mlp, parameter_space, n_jobs=-1, cv=3)
clf.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=MLPClassifier(), n_jobs=-1,
             param_grid={'alpha': [0.0001, 0.001],
                         'hidden_layer_sizes': [(500, 500, 500),
                                                (400, 400, 400),
                                                (300, 300, 300),
                                                (200, 200, 200)],
                         'max_iter': [1000, 2000, 3000, 4000],
                         'momentum': [0.9, 0.8, 0.6, 0.5]})

In [40]:
sorted(clf.cv_results_.keys())
# Best paramete set
print('Best parameters found:\n', clf.best_params_)


Best parameters found:
 {'alpha': 0.0001, 'hidden_layer_sizes': (500, 500, 500), 'max_iter': 1000, 'momentum': 0.5}


In [48]:
mlp = MLPClassifier(hidden_layer_sizes=(500,500,500),alpha=0.0001, momentum=0.5,max_iter=1000)
mlp.fit(x_train,y_train)
predictions = mlp.predict(x_test)


In [49]:
from sklearn.metrics import r2_score
print(confusion_matrix(y_test,predictions))
print()
from sklearn.metrics import r2_score
print("R2 Score:",r2_score(y_test, predictions))
print()
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[ 14   5   2   1   1   0   1]
 [  0  55   0   3   0   0   3]
 [  1   2  20   5   2   0   0]
 [  0   3   3 116   0   0   3]
 [  0   0   2   3  17   0   6]
 [  0   0   0   3   1  12   2]
 [  0   2   1   4   5   0  24]]

R2 Score: 0.5649305222150588

              precision    recall  f1-score   support

           0       0.93      0.58      0.72        24
           1       0.82      0.90      0.86        61
           2       0.71      0.67      0.69        30
           3       0.86      0.93      0.89       125
           4       0.65      0.61      0.63        28
           5       1.00      0.67      0.80        18
           6       0.62      0.67      0.64        36

    accuracy                           0.80       322
   macro avg       0.80      0.72      0.75       322
weighted avg       0.81      0.80      0.80       322

